### PR TITLE
Update about.md

### PR DESCRIPTION
**Pull request by EthnTuttle**

### CODE REVIEW

**Comment by tcharding** [comment]
Site looks interesting but I'm not personally comfortable linking to an project that is by a nym I don't know, has a suss-AF github account, and gives no justification in the PR. Sorry bro. Other maintainers views may differ.

**Comment by Kixunil** [comment]
I don't see a problem in what you described. It looks legit from quick look. The issue is that it's early stage.

But it's a question of policy what we want to include. The more projects we list the more legit we look but we also give them exposure. I think the rule should be roughly "whichever project significantly contributed to the Bitcoin ecosystem".

@EthnTuttle if you want more exposure consider posting here: https://github.com/rust-bitcoin/rust-bitcoin/discussions/categories/other-bitcoin-related-crates

**Comment by EthnTuttle** [comment]
No worries if this isn't merged. Came across the project and thought it was novel that it's using chain data directly instead of interfacing with a bitcoind instance. Seemed like an interesting use case for rust-bitcoin crates that I hadn't seen previously.

Will post in the discussion thread and close this PR, but do encourage discussion of acceptance criteria for the list.

**Comment by Kixunil** [comment]
> using chain data directly instead of interfacing with a bitcoind instance

That doesn't sound very secure.

**Pull request closed without merging**
