### PR TITLE
cookbook: Upgrade to latest bitcoin 0.32.0

### PR DESCRIPTION
**Pull request by tcharding**
Upgrade the cookbook to use the latest release of `rust-bitcoin`.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
utACK bd4391eeaa3926cf025832ed28374d6da7d83b09

**Comment by tcharding** [comment]
Are you watching this repo @storopoli? I'll wait a few days before merge in case you wanted to review. Thanks.

**Comment by storopoli** [comment]
No, I'm not but I will. Give me until tomorrow for a review? Thanks for the tagging.

**Comment by tcharding** [comment]
No rush man, take your time.

**Comment by storopoli** [comment]
I was going through the examples yesterday (wasn't aware of this PR) and I've seen that there's an uncommented line in

https://github.com/rust-bitcoin/rust-bitcoin.github.io/blob/bd4391eeaa3926cf025832ed28374d6da7d83b09/cookbook/src/tx_taproot.md?plain=1#L137-L148

see the `Txid, Witness,`.

Do we fix it in this PR or a different one?

EDIT: Done in #27.

**Review by storopoli — APPROVED** [review]
ACK bd4391eeaa3926cf025832ed28374d6da7d83b09

**Comment by tcharding** [comment]
Oh process fail, I can't ack this after the force push so can't merge it - my bad. Re-ack please @apoelstra or @storopoli, then i'll merge.

I rebased to pick up #27, I should not have done that, I'm used to Andrew doing the merging.

**Review by apoelstra — APPROVED** [review]
utACK 54b68a52a182b057fc79bec7c270f86403607810

**Comment by storopoli** [comment]
ACK 54b68a52a182b057fc79bec7c270f86403607810

**Pull request merged**
