### PR TITLE
fix: correct links and mentions to the v0.32.0 bitcoin

### PR DESCRIPTION
**Pull request by storopoli**
In the `Cargo.toml` of the tests we are already using `0.32.0`.
Hence, the doc links and mentions from `0.31.1` should be updated.

PS: I've added a minor inconsistency fix in [95f1401](https://github.com/rust-bitcoin/rust-bitcoin.github.io/pull/31/commits/95f1401ca572627bf835151fc848bee3ee026907)

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
utACK 95f1401ca572627bf835151fc848bee3ee026907

Didn't check that all the new docs.rs links work. Not sure how best to do that.

**Comment by storopoli** [comment]
That's the purpose of the [`check-links.yml`](https://github.com/rust-bitcoin/rust-bitcoin.github.io/actions/workflows/check-links.yml) CI.
I've haven't been following this repo (changed to follow it from now on).
It's failing due to outdated `secp256k1` docs links.
I'll correct those in a new commit here.

Give me until the end of the weekend.

**Comment by storopoli** [comment]
Done!
@apoelstra can you please do a manual run of [`check-links.yml`](https://github.com/rust-bitcoin/rust-bitcoin.github.io/actions/workflows/check-links.yml) for the branch `storopoli:storopoli/update-links-v0.32`?

I don't have the permissions necessary.

**Comment by apoelstra** [comment]
Hmm, I don't see a way to do it for branches outside of the repo. I think I should just ACK this PR and merge it and then we'll run it on master and see if we need to fix anything.

**Review by apoelstra — APPROVED** [review]
utACK 586a71cf9ecd9dee95b934b77aa178b8bd47fc72

**Comment by apoelstra** [comment]
BTW on master it looks like we have two(?) links to https://docs.rs/secp256k1/0.27.0/secp256k1/struct.Keypair.html which 404s.

**Comment by tcharding** [comment]
Oh sorry man, I ran it before and didn't comment here.

**Comment by tcharding** [comment]
I can't find those links to 0.27.0 locally?

**Comment by storopoli** [comment]
> BTW on master it looks like we have two(?) links to https://docs.rs/secp256k1/0.27.0/secp256k1/struct.Keypair.html which 404s.

Yes, but this is fixed in this PR, you've ran the `check-links` from the `master` branch.

I've ran the [file checking link manually](https://github.com/tcort/markdown-link-check) and here's the results (abbreviated with `<ABBR>`):

```bash
rust-bitcoin.github.io on  storopoli/update-links-v0.32 [?] took 6s 
❯ docker run -v ${PWD}:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:stable /tmp/cookbook/src/tx_segwit-v0.md
(node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: /tmp/cookbook/src/tx_segwit-v0.md
  <ABBR>
  50 links checked.

rust-bitcoin.github.io on  storopoli/update-links-v0.32 [?] took 15s 
❯ docker run -v ${PWD}:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:stable /tmp/cookbook/src/tx_taproot.md
(node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: /tmp/cookbook/src/tx_taproot.md

<ABBR>

  58 links checked.
```

**Review by tcharding — APPROVED** [review]
ACK 586a71cf9ecd9dee95b934b77aa178b8bd47fc72

**Comment by tcharding** [comment]
Thanks for fixing my mistakes!

**Comment by tcharding** [comment]
I'm not sure how we remember to not do this same mistake next time, currently either the dev or the reviewer has to remember. If I'm the dev again next time there is a reasonable chance I'll forget ...

**Comment by storopoli** [comment]
I'll try to help the burden and enforce these in the future as well

**Pull request merged**
